### ISSUE TITLE
License is expired?

### ISSUE THREAD

**Issue by cristianserban93** [dimensigon/tibero-docker#3]
I'm trying to deploy the container, but I'm getting a license expiration message.

**Comment by cristianserban93** [comment]
@danimoya, I've noticed you've updated it in the past. Can you do it again?

Thanks!

**Comment by danimoya** [comment]
Hi @cristianserban93 , thanks for mentioning it. I will set a remainder on my side for each 5 months.

If you wish, contact me at my email daniel.moya@knowtrade.eu , I would like to know how are you using Tibero and Docker.

Best regards

Daniel

**Comment by tjlee** [comment]
👋 
The latest docker image ca1793e2bec1 is expired. Is there any plans to update license?

**Comment by danimoya** [comment]
Hi All

I have updated the license key. Sorry for the delay. 

NEW
===
**Pros**: Now the license allows any hostname, it is not necessary to call it "dummy" anymore.
**Cons**: License valid for 90 days. I put a remainder to update this every 75 days.

**Comment by danimoya** [comment]
New repository: https://hub.docker.com/r/danimoya/tibero

**Comment by tjlee** [comment]
Thank you for update!
