### ISSUE TITLE
License expired!!

### ISSUE THREAD

**Issue by tugsuu88** [dimensigon/tibero-docker#4]

**Comment by danimoya** [comment]
Hi

I have updated the license key. Sorry for the delay. 

NEW
===
Pros: Now the license allows any hostname, it is not necessary to call it "dummy" anymore.
Cons: License valid for 90 days. I put a remainder to update this every 75 days.

**Comment by danimoya** [comment]
New repository: https://hub.docker.com/r/danimoya/tibero
